---
title: "data_analysis"
author: "Will Schrepferman"
date: "3/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(ggmap)
library(sf)
library(mapview)
library(skimr)
library(geosphere)
```

```{r}
raw_data <- read_excel("hospitals_raw.xlsx") %>%
  clean_names()

data <- raw_data %>%
  pivot_wider(names_from = x, values_from = y) %>%
  clean_names() %>%
  select(name, address_line_one, address_line_two, administrator, telephone, fax, type_of_ownership,
         type_of_hospital, staffed_beds, license_number, license_expire_date) %>%
  unnest() %>%
  mutate(address = paste(address_line_one, address_line_two, sep = ", ")) %>%
  select(name, address, type_of_hospital, staffed_beds, license_number)

geo_hosp_data <- geocode(data$address)

geo_hosp_data_append <- data %>%
  mutate_geocode(address)

write_csv(geo_hosp_data, "geo_hosp_data.csv")
write_csv(geo_hosp_data_append, "geo_hosp_data_append.csv")


indiana <- map_data('state', region = 'indiana')

ggplot(indiana, aes(x = long, y = lat)) + 
  geom_polygon(fill = "lightblue", color = "black") + 
  theme_void() +
  geom_point(aes(x = lon, y = lat), data = geo_hosp_data,
 alpha = .5, color="darkred", size = 3)



myMap <- get_map(location="indiana", source="google", zoom = 7)

p <- ggmap(myMap) +
  geom_point(aes(x = lon, y = lat), data = geo_hosp_data,
 alpha = .5, color="orange", size = 2.5) +
  scale_x_continuous(limits = c(-88.1, -84.6)) +
  scale_y_continuous(limits = c(37.76,42))

locations_sf <- st_as_sf(geo_data, coords = c("lon", "lat"), crs = 4326)
  
mapview(locations_sf)

read_excel("nad.xlsx")
```

```{r}
bigdata <- read_excel("Book2.xlsx") %>%
  clean_names()

sample_bigdata <- sample_n(bigdata, 1000)

geo_data_big_sample <- sample_bigdata %>%
  mutate(lon = longitude) %>%
  mutate(lat = latitude)

geo_data_big <- bigdata %>%
  mutate(lon = longitude) %>%
  mutate(lat = latitude)

p <- ggmap(myMap) +
  geom_point(aes(x = lon, y = lat), data = geo_data_big,
 alpha = .35, color="darkred", size = .005) +
  geom_point(aes(x = lon, y = lat), data = geo_hosp_data,
 alpha = .5, color="orange", size = 2.5) +
  scale_x_continuous(limits = c(-88.1, -84.6)) +
  scale_y_continuous(limits = c(37.76,42))

```

```{r}
geo_data_big_sample
geo_hosp_data_append

hosp_simple <- geo_hosp_data_append %>%
  select(name, lon, lat)

test <- "simple"
for(i in 1:179){
  name <- hosp_simple[[1]][i]
   
  name <- gsub(" ", "_", name, perl=TRUE)
  
  geo_data_big_sample <- geo_data_big_sample %>%
    mutate(!!paste("dist_from", name, sep = "_") := distm(c(lon, lat), c(hosp_simple[[2]][i], hosp_simple[[3]][i]), fun = distHaversine))
}

t <- 1
```



